#!/bin/bash
mkdir -p /tmp/storage_data
if [[ $# -gt 0 ]]; then
    for ((i = 0 ; i < $1 ; i++)); do
        file_name="/tmp/storage_data/tweet"$i".txt"
        touch $file_name
        echo "I'm the tweet number "$i >> $file_name
    done    
else
    echo "Usage : init_storage_data [FILE_COUNT]"
fi